<?php

namespace Database\Seeders;

use App\Models\Sekolah;
use Illuminate\Database\Seeder;

class SekolahSeeder extends Seeder
{
    public function run(): void
    {
        $schools = [
            // 1. Jakarta Selatan (SMP Utama)
            [
                'nama' => 'SMP Negeri 1 Merata',
                'npsn' => '20108942',
                'akreditasi' => 'A (Unggul - Nilai 96)',
                'status_sekolah' => 'Negeri',
                'jenjang' => 'SMP',
                'kepala_sekolah' => 'Dra. Hj. Sri Wahyuni, M.Pd.',
                'nip_kepsek' => '197405121998032001',
                'operator' => 'Ahmad Fauzi, S.Pd.',
                'alamat' => 'Jl. Merata Raya No. 45, Kebayoran Baru, Jakarta Selatan',
                'wilayah' => 'Jakarta Selatan',
                'kode_pos' => '12180',
                'telepon' => '(021) 789-0123',
                'email' => 'info@smpn1merata.sch.id',
                'website' => 'https://smpn1merata.sch.id',
                'kurikulum' => 'Kurikulum Merdeka Mandiri Berbagi',
                'total_siswa' => 360,
                'trend_siswa' => '+1% dari bulan lalu',
                'total_guru' => 28,
                'trend_guru' => '+2 baru semester ini',
                'total_kelas' => 6,
                'trend_kelas' => 'Stabil',
                'tingkat_kehadiran' => '94.2%',
                'trend_kehadiran' => '+0.5%',
                'lab_komputer' => 2,
                'lab_ipa' => 1,
            ],
            // 2. Jakarta Timur (SMK Utama)
            [
                'nama' => 'SMK Negeri 26 Jakarta',
                'npsn' => '20102601',
                'akreditasi' => 'A (Unggul - Nilai 97)',
                'status_sekolah' => 'Negeri',
                'jenjang' => 'SMK',
                'kepala_sekolah' => 'Drs. Purwanto, M.T.',
                'nip_kepsek' => '197003151996021002',
                'operator' => 'Bambang Irawan, S.Kom.',
                'alamat' => 'Jl. Balai Pustaka Baru I, Rawamangun, Jakarta Timur',
                'wilayah' => 'Jakarta Timur',
                'kode_pos' => '13220',
                'telepon' => '(021) 472-0384',
                'email' => 'admin@smkn26jkt.sch.id',
                'website' => 'https://smkn26jkt.sch.id',
                'kurikulum' => 'Kurikulum Merdeka SMK Pusat Keunggulan',
                'total_siswa' => 420,
                'trend_siswa' => '+3% dari bulan lalu',
                'total_guru' => 35,
                'trend_guru' => 'Stabil',
                'total_kelas' => 6,
                'trend_kelas' => 'Aktif',
                'tingkat_kehadiran' => '95.8%',
                'trend_kehadiran' => '+1.2%',
                'lab_komputer' => 4,
                'lab_ipa' => 2,
            ],
            // 3. Jakarta Timur (SD Utama)
            [
                'nama' => 'SD Negeri Merata 03',
                'npsn' => '20105521',
                'akreditasi' => 'A (Unggul)',
                'status_sekolah' => 'Negeri',
                'jenjang' => 'SD',
                'kepala_sekolah' => 'Hj. Nuraini, S.Pd.',
                'nip_kepsek' => '197808242003122004',
                'operator' => 'Dian Anggraini, S.Pd.',
                'alamat' => 'Jl. Pendidikan No. 3, Duren Sawit, Jakarta Timur',
                'wilayah' => 'Jakarta Timur',
                'kode_pos' => '13440',
                'telepon' => '(021) 861-5521',
                'email' => 'sdnmerata03@jakarta.sch.id',
                'website' => 'https://sdnmerata03.sch.id',
                'kurikulum' => 'Kurikulum Merdeka Mandiri Belajar',
                'total_siswa' => 240,
                'trend_siswa' => 'Stabil',
                'total_guru' => 18,
                'trend_guru' => 'Stabil',
                'total_kelas' => 6,
                'trend_kelas' => 'Aktif',
                'tingkat_kehadiran' => '96.5%',
                'trend_kehadiran' => '+0.8%',
                'lab_komputer' => 1,
                'lab_ipa' => 0,
            ],
            // 4. Kepulauan Seribu (Wilayah 3T / Pesisir)
            [
                'nama' => 'SMP Negeri 45 Pulau Seribu',
                'npsn' => '20109881',
                'akreditasi' => 'B (Baik)',
                'status_sekolah' => 'Negeri',
                'jenjang' => 'SMP',
                'kepala_sekolah' => 'Hendra Saputra, S.Pd.',
                'nip_kepsek' => '198104102008011015',
                'operator' => 'Rahmat Hidayat, S.Pd.',
                'alamat' => 'Pulau Kelapa, Kepulauan Seribu Utara',
                'wilayah' => 'Kepulauan Seribu',
                'kode_pos' => '14540',
                'telepon' => '(021) 988-1234',
                'email' => 'smpn45seribu@jakarta.sch.id',
                'website' => 'https://smpn45seribu.sch.id',
                'kurikulum' => 'Kurikulum Merdeka Mandiri Berubah',
                'total_siswa' => 180,
                'trend_siswa' => '-2% dari bulan lalu',
                'total_guru' => 14,
                'trend_guru' => 'Stabil',
                'total_kelas' => 3,
                'trend_kelas' => 'Aktif',
                'tingkat_kehadiran' => '88.5%',
                'trend_kehadiran' => '+1.5%',
                'lab_komputer' => 1,
                'lab_ipa' => 1,
            ],
            // 5. Jakarta Selatan (SMA)
            [
                'nama' => 'SMA Negeri 70 Jakarta',
                'npsn' => '20107001',
                'akreditasi' => 'A (Unggul)',
                'status_sekolah' => 'Negeri',
                'jenjang' => 'SMA',
                'kepala_sekolah' => 'Bambang Sutrisno, M.Si.',
                'nip_kepsek' => '196902141994031005',
                'operator' => 'Anita Wulandari, S.Pd.',
                'alamat' => 'Jl. Bulungan No. 1, Kebayoran Baru, Jakarta Selatan',
                'wilayah' => 'Jakarta Selatan',
                'kode_pos' => '12130',
                'telepon' => '(021) 720-1234',
                'email' => 'info@sman70jkt.sch.id',
                'website' => 'https://sman70jkt.sch.id',
                'kurikulum' => 'Kurikulum Merdeka Mandiri Berbagi',
                'total_siswa' => 380,
                'trend_siswa' => '+2% dari bulan lalu',
                'total_guru' => 32,
                'trend_guru' => '+1 guru',
                'total_kelas' => 4,
                'trend_kelas' => 'Aktif',
                'tingkat_kehadiran' => '97.2%',
                'trend_kehadiran' => '+0.3%',
                'lab_komputer' => 3,
                'lab_ipa' => 2,
            ],
            // 6. Jakarta Barat
            [
                'nama' => 'SMP Negeri 111 Jakarta',
                'npsn' => '20111101',
                'akreditasi' => 'A',
                'status_sekolah' => 'Negeri',
                'jenjang' => 'SMP',
                'kepala_sekolah' => 'Drs. H. Mulyadi',
                'nip_kepsek' => '197108191997021003',
                'operator' => 'Syaifullah, S.Pd.',
                'alamat' => 'Jl. Bhakti VII No. 2, Palmerah, Jakarta Barat',
                'wilayah' => 'Jakarta Barat',
                'kode_pos' => '11480',
                'telepon' => '(021) 548-1111',
                'email' => 'smpn111@dki.belajar.id',
                'website' => 'https://smpn111jkt.sch.id',
                'kurikulum' => 'Kurikulum Merdeka',
                'total_siswa' => 320,
                'trend_siswa' => 'Stabil',
                'total_guru' => 24,
                'trend_guru' => 'Stabil',
                'total_kelas' => 6,
                'trend_kelas' => 'Aktif',
                'tingkat_kehadiran' => '94.8%',
                'trend_kehadiran' => 'Stabil',
                'lab_komputer' => 2,
                'lab_ipa' => 1,
            ],
            // 7. Jakarta Pusat
            [
                'nama' => 'SMP Negeri 1 Jakarta',
                'npsn' => '20100114',
                'akreditasi' => 'A',
                'status_sekolah' => 'Negeri',
                'jenjang' => 'SMP',
                'kepala_sekolah' => 'Dra. Ratna Juwita, M.Pd.',
                'nip_kepsek' => '197502181999032002',
                'operator' => 'Kurniawan, S.Pd.',
                'alamat' => 'Jl. Cikini Raya No. 87, Menteng, Jakarta Pusat',
                'wilayah' => 'Jakarta Pusat',
                'kode_pos' => '10330',
                'telepon' => '(021) 314-0114',
                'email' => 'smpn1@dki.belajar.id',
                'website' => 'https://smpn1jkt.sch.id',
                'kurikulum' => 'Kurikulum Merdeka',
                'total_siswa' => 340,
                'trend_siswa' => '+1%',
                'total_guru' => 26,
                'trend_guru' => 'Stabil',
                'total_kelas' => 6,
                'trend_kelas' => 'Aktif',
                'tingkat_kehadiran' => '96.0%',
                'trend_kehadiran' => '+0.5%',
                'lab_komputer' => 2,
                'lab_ipa' => 1,
            ],
            // 8. Jakarta Utara
            [
                'nama' => 'SMP Negeri 30 Jakarta',
                'npsn' => '20103001',
                'akreditasi' => 'A',
                'status_sekolah' => 'Negeri',
                'jenjang' => 'SMP',
                'kepala_sekolah' => 'H. Sukardi, S.Pd., M.M.',
                'nip_kepsek' => '197204121998021004',
                'operator' => 'Farid Wajdi, S.Pd.',
                'alamat' => 'Jl. Anggrek No. 4, Koja, Jakarta Utara',
                'wilayah' => 'Jakarta Utara',
                'kode_pos' => '14230',
                'telepon' => '(021) 439-3001',
                'email' => 'smpn30@dki.belajar.id',
                'website' => 'https://smpn30jkt.sch.id',
                'kurikulum' => 'Kurikulum Merdeka',
                'total_siswa' => 310,
                'trend_siswa' => 'Stabil',
                'total_guru' => 22,
                'trend_guru' => 'Stabil',
                'total_kelas' => 6,
                'trend_kelas' => 'Aktif',
                'tingkat_kehadiran' => '93.5%',
                'trend_kehadiran' => '+0.4%',
                'lab_komputer' => 1,
                'lab_ipa' => 1,
            ],
        ];

        foreach ($schools as $school) {
            Sekolah::create($school);
        }
    }
}
